sudo: false

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - autopoint
      - xsltproc

script:
 - cat /proc/self/uid_map
 - cat /proc/self/status
 - systemd-detect-virt
 - /bin/false

# vim:et:ts=2:sw=2
