sudo: false

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - autopoint
      - xsltproc
      - expect

script:
 - cat /proc/self/uid_map
 - cat /proc/self/status
 - systemd-detect-virt
 - ./autogen.sh --without-selinux --disable-man
 - grep ENABLE_ config.status
 - make
 - sudo make install
 - (cd tests; sudo ./run_some; cat testsuite.log)


# vim:et:ts=2:sw=2
