name: CI

on:
  push:
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: debug
      run: |
        id
        which bash
        whoami
        env
        ps -ef
        pwd
        cat /proc/self/uid_map
        cat /proc/self/status
        systemd-detect-virt
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install automake autopoint xsltproc gettext expect byacc libtool
    - name: configure
      run: |
        ./autogen.sh --without-selinux --disable-man
        grep ENABLE_ config.status
    - run: make
    - run: make install DESTDIR=${HOME}/rootfs
    - run: sudo make install
    - run: |
        cd tests
        run_test() {
            echo "XXX Running $1 from $(pwd)"
            if sudo $1 > $1.log; then
                succeeded=$((succeeded+1))
                echo -n "+"
            else
                failed=$((failed+1))
                failed_tests="$failed_tests $1"
                echo -n "-"
            fi
            cat $1.log >> testsuite.log
            [ -f /etc/passwd.lock ] && echo $1 /etc/passwd.lock || true
            [ -f /etc/group.lock ] && echo $1 /etc/group.lock || true
            [ -f /etc/shadow.lock ] && echo $1 /etc/shadow.lock || true
            [ -f /etc/gshadow.lock ] && echo $1 /etc/gshadow.lock || true
            if [ "$(stat -c"%G" /etc/shadow)" != "shadow" ]
            then
                echo $1
                ls -l /etc/shadow
                sudo chgrp shadow /etc/shadow
            fi
            if [ -d /nonexistent ]
            then
                echo $1 /nonexistent
                sudo rmdir /nonexistent
            fi
        }
        build_path=$(git rev-parse --show-toplevel)
        sudo find "${build_path}" -name "*.gcda" -delete
        run_test ./su/01/su_root.test
        run_test ./su/01/su_user.test
        cat testsuite.log
